baseURL = "https://allyouneedtoknow.tips/"
theme = "hugrid"
defaultContentLanguage = "en"
languageCode = "en-US"
title = "All you need to know"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-156024128-1"
enableRobotsTXT = true

[languages.en]
  weight = 0
  languageName = "English"
  contentDir = "content/en"

[languages.it]
  weight = 10
  languageName = "Italian"
  contentDir = "content/it"

[params]
    # Meta
    author = "co-autori Alessandro Travi e Denise Caggio"
    description = "Consigli di viaggio"
    keywords = "consigli di viaggio"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Footer text
    footertext = "Made with ♥ by [Alessandro](https://www.instagram.com/alessandro.travi/) and [Denise](https://www.instagram.com/nonblonde.d/)"

    # add extra-css
    custom_css = ['css/custom.css']
    # add extra-css
    custom_js = ['js/custom.js']
